In [78]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.12.1+cu113


## Introduction to tensors




### Creating tensors

In [79]:
# Scaler
scaler = torch.tensor(7)
scaler

tensor(7)

In [80]:
scaler.ndim

0

In [81]:
# Get tensor back as python int
scaler.item()

7

In [82]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [83]:
vector.ndim

1

In [84]:
vector.shape

torch.Size([2])

In [85]:
scaler.shape

torch.Size([])

In [86]:
# Matrix
matrix = torch.tensor([[7,8],
                       [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [87]:
matrix.ndim

2

In [88]:
matrix[0]

tensor([7, 8])

In [89]:
matrix[1]

tensor([ 9, 10])

In [90]:
matrix[0][1]

tensor(8)

In [91]:
matrix.shape

torch.Size([2, 2])

In [92]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3,6,9],
                        [2,4,5]]])

In [93]:
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [94]:
TENSOR.ndim

3

In [95]:
TENSOR.shape

torch.Size([1, 3, 3])

In [96]:
ex_tensor = torch.tensor([[[[4,5,7],
                            [6,8,9],
                            [7,9,9],
                            [10,42,10]]]])

In [97]:
ex_tensor.ndim

4

In [98]:
ex_tensor.shape

torch.Size([1, 1, 4, 3])

### Random tensors

In [99]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.2009, 0.4930, 0.5407, 0.6399],
        [0.7357, 0.0979, 0.0306, 0.2559],
        [0.5630, 0.4170, 0.9437, 0.9817]])

In [100]:
random_tensor.ndim

2

In [101]:
random_tensor.shape

torch.Size([3, 4])

In [102]:
random_image_size = torch.rand(size=(224,224,3))
random_image_size

tensor([[[0.6543, 0.2785, 0.6603],
         [0.2177, 0.4641, 0.7866],
         [0.4920, 0.9187, 0.7706],
         ...,
         [0.3388, 0.3724, 0.2010],
         [0.4197, 0.5215, 0.6136],
         [0.2508, 0.1562, 0.2174]],

        [[0.5294, 0.5990, 0.3160],
         [0.5897, 0.7742, 0.0530],
         [0.1224, 0.6023, 0.8783],
         ...,
         [0.2913, 0.0806, 0.0358],
         [0.0876, 0.4872, 0.7553],
         [0.6813, 0.7158, 0.4102]],

        [[0.8623, 0.6859, 0.3446],
         [0.4024, 0.2458, 0.4369],
         [0.7173, 0.4777, 0.2932],
         ...,
         [0.2901, 0.0306, 0.8446],
         [0.0458, 0.3289, 0.9146],
         [0.8061, 0.5124, 0.2674]],

        ...,

        [[0.5530, 0.5849, 0.8628],
         [0.8863, 0.8685, 0.7354],
         [0.6928, 0.3922, 0.8501],
         ...,
         [0.5414, 0.6377, 0.4947],
         [0.7662, 0.6781, 0.6739],
         [0.5933, 0.4304, 0.6629]],

        [[0.5211, 0.2212, 0.8778],
         [0.7462, 0.7638, 0.6996],
         [0.

In [103]:
random_image_size.shape

torch.Size([224, 224, 3])

In [104]:
random_image_size.ndim

3

### Zeros and ones

In [105]:
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [106]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [107]:
# ones
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [108]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [109]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
one_to_end = torch.arange(start=0, end=100, step=7)
one_to_end

tensor([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [111]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_end)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [112]:
len(ten_zeros)

15

### Tensor datatypes

In [113]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [114]:
float_32_tensor.dtype

torch.float32

In [115]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [116]:
float_32_tensor*float_16_tensor


tensor([ 9., 36., 81.])

In [117]:
int_32_tensor = torch.tensor([3,6,8],dtype=torch.int32)
int_32_tensor

tensor([3, 6, 8], dtype=torch.int32)

In [118]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 72.])

### Manipulating tensors

In [119]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [120]:
tensor * 10

tensor([10, 20, 30])

In [121]:
tensor

tensor([1, 2, 3])

In [122]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [123]:
tensor

tensor([-9, -8, -7])

In [124]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])

In [125]:
torch.multiply(tensor, 10)


tensor([10, 20, 30])

In [126]:
torch.add(tensor, 20)

tensor([21, 22, 23])

In [127]:
tensor

tensor([1, 2, 3])

In [128]:
torch.sub(tensor, 20)

tensor([-19, -18, -17])

In [129]:
tensor

tensor([1, 2, 3])

### Matrix multiplication

In [130]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [131]:
tensor * tensor

tensor([1, 4, 9])

In [132]:
tensor.matmul(tensor)

tensor(14)

In [133]:
tensor @ tensor

tensor(14)

In [134]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)


In [135]:
tensor_A.shape

torch.Size([3, 2])

In [136]:
tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

In [139]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 76., 103.],
        [100., 136.]])

In [140]:
tensor_A.T

tensor([[1., 3., 5.],
        [2., 4., 6.]])

In [141]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

### Finding the min, max, mean, sum, etc

In [142]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [143]:
x.min()

tensor(0)

In [144]:
x.max()

tensor(90)

In [146]:
# Mean doesnot work without float
x.type(torch.float32).mean()

tensor(45.)

In [147]:
x.sum()

tensor(450)

### Positional min/max

In [148]:
x.argmax()

tensor(9)

In [149]:
x.argmin()

tensor(0)

### Change tensor datatype


In [150]:
tensor = torch.arange(10., 100., 10.)
tensor.dtype

torch.float32

In [151]:
tensor_float16 = tensor.type(torch.float16)


In [152]:
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [153]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing

In [154]:
x = torch.arange(1.,8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [156]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [157]:
z = x.view(1, 7)
z

tensor([[1., 2., 3., 4., 5., 6., 7.]])

In [161]:
z.shape

torch.Size([1, 7])

In [158]:
x

tensor([1., 2., 3., 4., 5., 6., 7.])

In [162]:
x.shape

torch.Size([7])

In [159]:
z[:,0] = 5
z

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [160]:
x

tensor([5., 2., 3., 4., 5., 6., 7.])

In [166]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.]])

In [167]:
torch.vstack([x,x,x])

tensor([[5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.],
        [5., 2., 3., 4., 5., 6., 7.]])

In [168]:
torch.hstack([x, x, x])

tensor([5., 2., 3., 4., 5., 6., 7., 5., 2., 3., 4., 5., 6., 7., 5., 2., 3., 4.,
        5., 6., 7.])

In [169]:
# squeeze
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7.]])

In [170]:
x_reshaped.shape

torch.Size([1, 7])

In [171]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7.])

In [172]:
x_reshaped.squeeze().shape

torch.Size([7])

In [173]:
x = torch.zeros(2, 1, 2, 1, 2)
x

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [174]:
x.size()

torch.Size([2, 1, 2, 1, 2])

In [175]:
y = torch.squeeze(x)
y

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [176]:
y.shape

torch.Size([2, 2, 2])

In [177]:
y = torch.squeeze(x, 0)
y

tensor([[[[[0., 0.]],

          [[0., 0.]]]],



        [[[[0., 0.]],

          [[0., 0.]]]]])

In [178]:
y.shape

torch.Size([2, 1, 2, 1, 2])

In [179]:
y = torch.squeeze(x,1)
y

tensor([[[[0., 0.]],

         [[0., 0.]]],


        [[[0., 0.]],

         [[0., 0.]]]])

In [180]:
y.size()

torch.Size([2, 2, 1, 2])

### Indexing(selecting data from tensors)


In [181]:
x = torch.arange(1, 10)

In [182]:
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [185]:
x.reshape(1, 3, 3)

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [186]:
x.shape

torch.Size([9])

In [187]:
x = x.reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [188]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [189]:
x[0][0]

tensor([1, 2, 3])

In [190]:
x[0][0][0]

tensor(1)

In [191]:
x[:, 0]

tensor([[1, 2, 3]])

### PyTorch tensors & Numpy

In [192]:
import numpy as np
array = np.arange(1.0, 8.0)
array

array([1., 2., 3., 4., 5., 6., 7.])

In [194]:
tensor = torch.from_numpy(array).type(torch.float32)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.])

In [195]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [1]:
# Check gpu
!nvidia-smi

Sat Sep 10 12:31:41 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [3]:
import torch
torch.cuda.is_available()

True